CREATE TABLE usuarios(
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(25) NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);
